apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend
type: Opaque
stringData:
  MONGO_URI: "mongodb://taskuser:taskpassword123@mongo-mongodb-0.mongo-mongodb-headless.database.svc.cluster.local:27017,mongo-mongodb-1.mongo-mongodb-headless.database.svc.cluster.local:27017,mongo-mongodb-2.mongo-mongodb-headless.database.svc.cluster.local:27017/tasksdb?replicaSet=rs0&authSource=admin"
