apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: backend-mongo-secret
  namespace: backend
spec:
  vaultAuthRef: vault-auth-backend
  mount: secret
  type: kv-v2
  path: backend/mongo
  refreshAfter: 30s
  destination:
    name: backend-secrets
    create: true
